#开放端口
server:
  port: 10002

spring:
  #服务名
  application:
    name: files-receive
  #环境
  profiles:
    active: dev
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #json时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8